version: "3"

services:
  server:
    container_name: NODEJS_SERVER_MEDIUM
    build: "."
    volumes:
      - ./:/node-app
      - ./node_modules:/node-app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - db
    links:
      - db
    ports:
      - 4000:4000

  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: vuttr
